# -*- coding: utf-8 -*-
"""Act8.- DashBoard con porgramación python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qSXMmeqt3eGHCm7vNMSPJ2oN1nmirOoM
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import kagglehub
import streamlit as st

# Configuración inicial de la página de Streamlit
st.set_page_config(page_title="Dashboard de Sueldos Federales", layout="wide")

st.title("Dashboard de los sueldos Mexicanos")
st.markdown("Dashboard que tiene como proposito ")


@st.cache_data
def load_data():
    path = kagglehub.dataset_download("ivansabik/mexican-federal-government-salaries")
    file_path = os.path.join(path, 'salaries.csv')


    df = pd.read_csv(file_path, encoding='utf-8')
    df_sample = df.sample(n=500, random_state=0)

    df_sample['montoneto'] = pd.to_numeric(df_sample['montoneto'], errors='coerce')
    df_sample['montobruto'] = pd.to_numeric(df_sample['montobruto'], errors='coerce')

    return df_sample

with st.spinner("Descargando datos de kaggle"):
    df_orig = load_data()


st.sidebar.header("Filtros para el data set")

entidades = sorted(df_orig['entidadfederativa'].dropna().unique())
entidades_sel = st.sidebar.multiselect("1. entidad federativa", entidades, default=entidades[:3])

sujetos = sorted(df_orig['sujetobligado'].dropna().unique())
sujetos_sel = st.sidebar.multiselect("2. Sujeto obligado", sujetos, default=sujetos[:5] if len(sujetos) > 5 else sujetos)

sueldo_sel = st.sidebar.slider("3. Suelfdo Neto ", float(df_orig['montoneto'].min()), float(df_orig['montoneto'].max()), (float(df_orig['montoneto'].min()), float(df_orig['montoneto'].max())))
bruto_sel = st.sidebar.slider("4. Sueldo Bruto ", float(df_orig['montobruto'].min()), float(df_orig['montobruto'].max()), (float(df_orig['montobruto'].min()), float(df_orig['montobruto'].max())))
cargo_search = st.sidebar.text_input("5. Buscar por Cargo", "")

df_f = df_orig[
    (df_orig['entidadfederativa'].isin(entidades_sel)) &
    (df_orig['sujetoobligado'].isin(sujetos_sel)) &
    (df_orig['montoneto'].between(sueldo_sel[0], sueldo_sel[1])) &
    (df_orig['montobruto'].between(bruto_sel[0], bruto_sel[1]))
]

if cargo_search:
    df_f = df_f[df_f['cargo'].str.contains(cargo_search, case=False, na=False)]


st.header("Vista de Datos Filtrados")
st.write(f"Mostrando **{df_f.shape[0]}** registros de **{df_orig.shape[0]}** en la muestra.")
st.dataframe(df_f, use_container_width=True)

st.header("Estadísticas Descriptivas")
col1, col2, col3 = st.columns(3)
col1.metric("Media Sueldo Neto", f"${df_f['montoneto'].mean():,.2f}", f"${df_f['montoneto'].mean() - df_orig['montoneto'].mean():,.2f} vs Orig")
col2.metric("Máximo Sueldo Neto", f"${df_f['montoneto'].max():,.2f}", f"${df_f['montoneto'].max() - df_orig['montoneto'].max():,.2f} vs Orig")
col3.metric("Sueldo Bruto Promedio", f"${df_f['montobruto'].mean():,.2f}", f"${df_f['montobruto'].mean() - df_orig['montobruto'].mean():,.2f} vs Orig")


st.header("Gráficos Dinámicos")

if df_f.empty:
    st.warning("No hay datos que coincidan con los filtros.")
else:

    c1, c2 = st.columns(2)
    with c1:
        fig, ax = plt.subplots()
        sns.histplot(df_f['montoneto'], kde=True, ax=ax, color='skyblue')
        st.subheader("G1: Distribución del Monto Neto")
        st.pyplot(fig)
    with c2:
        fig, ax = plt.subplots()
        sns.scatterplot(data=df_f, x='montobruto', y='montoneto', ax=ax, color='purple', alpha=0.7)
        st.subheader("G2: Monto Neto vs Monto Bruto")
        st.pyplot(fig)


    c3, c4 = st.columns(2)
    with c3:
        fig, ax = plt.subplots()
        top_sujetos = df_f.groupby('sujetoobligado')['montoneto'].mean().sort_values(ascending=False).head(5)
        sns.barplot(x=top_sujetos.values, y=top_sujetos.index, ax=ax, palette='viridis')
        st.subheader("G3: Top 5 Sujetos con Mayor Sueldo Promedio")
        st.pyplot(fig)
    with c4:
        fig, ax = plt.subplots()
        sns.boxenplot(data=df_f, x='entidadfederativa', y='montoneto', ax=ax) # Boxenplot es más limpio visualmente
        plt.xticks(rotation=45, ha='right')
        st.subheader("G4: Comparativo de Sueldo Neto por Entidad")
        st.pyplot(fig)


    c5, c6 = st.columns(2)
    with c5:
        fig, ax = plt.subplots()
        counts = df_f['entidadfederativa'].value_counts()
        if not counts.empty:
            ax.pie(counts, labels=counts.index, autopct='%1.1f%%', startangle=90, colors=sns.color_palette('pastel'))
        st.subheader("G5: Proporción por Entidad Federativa")
        st.pyplot(fig)
    with c6:
        fig, ax = plt.subplots()
        top_areas = df_f['area'].value_counts().head(5)
        sns.countplot(data=df_f[df_f['area'].isin(top_areas.index)], y='area', ax=ax, order=top_areas.index, palette='magma')
        st.subheader("G6: Relación de Sueldo Neto por Tipo de Área (Top 5)")
        st.pyplot(fig)